LexiconGarage/Controllers/Members25Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LexiconGarage.DAL;
using LexiconGarage.Models;

namespace LexiconGarage.Controllers {
    public class Members25Controller : Controller {
        private GarageContext db = new GarageContext();

        // GET: Members25
        public ActionResult Index() {
            var allMembers = db.Members.ToList();
            ViewBag.SearchTableInfo = "Totalt antal medlemmar: " + allMembers.Count.ToString();
            var tuple = new Tuple<IEnumerable<Member>, Member>(allMembers, new Member());
            return View("Index", tuple);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AllMembersSearch([Bind(Include = "Id,UserName, Name, TelNumber, Address")] Member member)
        {
            string strUserName = string.IsNullOrEmpty(Request.Form["Item2.UserName"]) ? "" : Request.Form["Item2.UserName"];
            string strName = string.IsNullOrEmpty(Request.Form["Item2.Name"]) ? "" : Request.Form["Item2.Name"];

            if (member == null)
            {
                member = new Member();
            }
            // Populerar sök-värdena till vehicle-ojektet, då behåller vi användarens inmatade värden då Search-sidan återladdas med resultatlistan/tabellen 
            member.UserName = string.IsNullOrEmpty(strUserName) ? "" : strUserName;
            member.Name = string.IsNullOrEmpty(strName) ? "" : strName;

            var subsetListOfMembers = DoSearch(strUserName, strName);

            var tuple = new Tuple<IEnumerable<Member>, Member>(subsetListOfMembers, member);
            ViewBag.SearchTableInfo = "Antal matchande poster: " + subsetListOfMembers.Count.ToString();
            return View("Index", tuple);
        }


        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AllMembersResetSearch(string userName)
        {
            var anEmptyList = new List<Member>();  
            var tuple = new Tuple<IEnumerable<Member>, Member>(anEmptyList, new Member());
            return View("Index", tuple);
        }



        // GET: Members25/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null) {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members25/Register
        public ActionResult Register() {
            return View();
        }

        // POST: Members25/Register
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "Id,UserName,Name,TelNumber,Address")] Member member) {
            if (ModelState.IsValid) {
                if (!UserNameAlreadyRegistered(member.UserName)) {
                    db.Members.Add(member);
                    db.SaveChanges();
                    return RedirectToAction("Details", new { Id = member.Id });
                } else {
                    ViewBag.ErrorMessage = "Felmeddelande: Det finns redan en medlem " +
                        "med användarnamn '" + member.UserName + "' registrerad.";
                }
            }

            return View(member);
        }

        // GET: Members25/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null) {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members25/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserName,Name,TelNumber,Address")] Member member) {
            if (ModelState.IsValid) {
                var oldUserName = db.Members.Where(m => m.Id == member.Id)
                    .Select(m => m.UserName).FirstOrDefault();
                if (oldUserName == member.UserName || !UserNameAlreadyRegistered(member.UserName)) {
                    db.Entry(member).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Details", new { Id = member.Id });
                }
                ViewBag.ErrorMessage = "Felmeddelande: Det finns redan en medlem " +
                        "med användarnamn '" + member.UserName + "' registrerad.";
            }
            return View(member);
        }

        // GET: Members25/Unregister/5
        public ActionResult Unregister(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null) {
                return HttpNotFound();
            } else {
                if (member.NumberOfVehicles != 0) {
                    ViewBag.ErrorMessage = "Felmeddelande: Medlemmen kan inte avregistreras eftersom fordon finns parkerade.";
                    return View("Details", member);
                }
            }
            return View(member);
        }

        // POST: Members25/Unregister/5
        [HttpPost, ActionName("Unregister")]
        [ValidateAntiForgeryToken]
        public ActionResult UnregisterConfirmed(int id) {
            Member member = db.Members.Find(id);
            var userName = member.UserName;
            db.Members.Remove(member);
            db.SaveChanges();
            ViewBag.InfoMessage = "Medlemmen '" + userName + "' har avregistrerats.";
            return View("Index", db.Members.ToList());
        }

        public List<Member> DoSearch(string strUserName, string strName)
        {
            var subsetListOfVehicles = new List<Member>();

            if (strUserName.Length > 0 || strName.Length > 0)
                subsetListOfVehicles = (from x in db.Members.ToList()
                                        where   x.UserName.ToString().ToUpper().Contains(strUserName.ToUpper()) &&
                                                x.Name.ToString().ToUpper().Contains(strName.ToUpper())
                                        select x).ToList();

            return subsetListOfVehicles;
        }


        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool UserNameAlreadyRegistered(string userName) {
            var count = db.Members.Where(m => m.UserName == userName).ToList().Count;
            return count != 0;
        }
    }
}

LexiconGarage/Controllers/Vehicles25Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LexiconGarage.DAL;
using LexiconGarage.Models;

namespace LexiconGarage.Controllers {
    public class Vehicles25Controller : Controller {
        private GarageContext db = new GarageContext();

        // GET: Vehicles25
        public ActionResult Index() {
            var model = new Garage(db);
            return View(model);
        }

        public ActionResult About() {
            return View();
        }

        // GET: Vehicles25/AllVehicles
        public ActionResult AllVehicles()
        {
            ViewBag.VBagVehicleList = new SelectList(db.VehicleTypes, "Id", "TypeInSwedish", 0);
            var vehicles = db.Vehicles.Include(v => v.Member).Include(v => v.VehicleType);
            ViewBag.SearchTableInfo = "Totalt antal fordon i garaget: " + vehicles.ToList().Count.ToString();
            var tuple = new Tuple<IEnumerable<Vehicle>, Vehicle>(vehicles, new Vehicle());

            return View("AllVehicles", tuple);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AllVehiclesParked(string RegNo, string brand, string color)
        {
            var allVehicles = db.Vehicles.ToList();

            ViewBag.SearchTableInfo = "Totalt antal fordon i garaget: " + allVehicles.Count.ToString();
            ViewBag.VBagVehicleList = new SelectList(db.VehicleTypes, "Id", "TypeInSwedish");
            var tuple = new Tuple<IEnumerable<Vehicle>, Vehicle>(allVehicles, new Vehicle());
            return View("AllVehicles", tuple);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AllVehicles(string RegNo, string brand, string color)
        {
            var allVehicles = db.Vehicles.ToList();

            ViewBag.SearchTableInfo = "Totalt antal fordon i garaget: " + allVehicles.Count.ToString();
            ViewBag.VBagVehicleList = new SelectList(db.VehicleTypes, "Id", "TypeInSwedish");
            var tuple = new Tuple<IEnumerable<Vehicle>, Vehicle>(allVehicles, new Vehicle());
            return View("Search", tuple);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AllVehiclesSearch([Bind(Include = "Id,VehicleTypeId,RegNo,MemberId,NumberOfWheels,Brand,Model,Weight,ParkingSlot")] Vehicle vehicle)
        {
            int intVehicleTypeId = 0;
            bool result = false;
            string strRegNo = string.IsNullOrEmpty(Request.Form["Item2.RegNo"]) ? "" : Request.Form["Item2.RegNo"];
            string strUserName = string.IsNullOrEmpty(Request.Form["Item2.Member.UserName"]) ? "" : Request.Form["Item2.Member.UserName"];
            string strBrand = string.IsNullOrEmpty(Request.Form["Item2.Brand"]) ? "" : Request.Form["Item2.Brand"];            
            string strType = Request.Form["VBagVehicleList"];

            if (vehicle != null)
            {
                vehicle = new Vehicle();
                vehicle.Member = new Member();
            }
            // Populerar sök-värdena till vehicle-ojektet, då behåller vi användarens 
            // inmatade värden då Search-sidan återladdas med resultatlistan/tabellen 
            vehicle.RegNo = string.IsNullOrEmpty(strRegNo) ? "" : strRegNo;
            vehicle.Brand = string.IsNullOrEmpty(strBrand) ? "" : strBrand;
            vehicle.Member.UserName = string.IsNullOrEmpty(strUserName) ? "" : strUserName;
            // VehicleType
            strType = (string.IsNullOrEmpty(strType) || strType.Equals("0")) ? "" : strType;
            result = Int32.TryParse(strType, out intVehicleTypeId);
            if (result)
            {
                vehicle.VehicleType = db.VehicleTypes.Find(intVehicleTypeId);
            }

            var subsetListOfVehicles = DoSearch(strRegNo, strUserName, strBrand, strType, vehicle);

            var tuple = new Tuple<IEnumerable<Vehicle>, Vehicle>(subsetListOfVehicles, vehicle);
            ViewBag.SearchTableInfo = "Antal matchande poster: " + subsetListOfVehicles.Count.ToString();
            ViewBag.VBagVehicleList = new SelectList(db.VehicleTypes, "Id", "TypeInSwedish", intVehicleTypeId);
            return View("AllVehicles", tuple);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AllVehiclesResetSearch(string RegNo, string brand, string color)
        {
            //var TestRegNr = Request.Form["Item2.RegNo"]; 
            //var view =  Request.Form["Item2.viewName"];

            var anEmptyList = new List<Vehicle>();
            ViewBag.VBagVehicleList = new SelectList(db.VehicleTypes, "Id", "TypeInSwedish");
            var tuple = new Tuple<IEnumerable<Vehicle>, Vehicle>(anEmptyList, new Vehicle());
            return View("AllVehicles", tuple);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResetSearch(string RegNo, string brand, string color)
        {         
            var anEmptyList = new List<Vehicle>();
            ViewBag.VBagVehicleList = new SelectList(db.VehicleTypes, "Id", "TypeInSwedish");
            var tuple = new Tuple<IEnumerable<Vehicle>, Vehicle>(anEmptyList, new Vehicle());
            return View("Search", tuple);
        }


        // GET: Vehicles25/Details/5
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null) {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // GET: Vehicles25/CheckInForMember
        //public ActionResult CheckInForMember([Bind(Include = "MemberId")] Vehicle vehicle) {
        //    var UserName = db.Members.Where(m => m.Id == vehicle.MemberId).Select(m => m.UserName).FirstOrDefault();
        //    if (UserName != null) {
        //        ViewBag.UserName = UserName;
        //        ViewBag.MemberFixed = true;
        //    }
        //    else {
        //        ViewBag.MemberFixed = false;
        //        ViewBag.MemberId = new SelectList(db.Members, "Id", "UserName");
        //    }
        //    ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "TypeInSwedish");
        //    return View("CheckIn", vehicle);
        //}

        // GET: Vehicles25/CheckIn
        public ActionResult CheckIn(int? id) {
            if (new Garage(db).EmptySlots() != 0) {
                if (id == null) {
                    ViewBag.MemberId = new SelectList(db.Members, "Id", "UserName");
                } else {
                    ViewBag.MemberId = new SelectList(db.Members, "Id", "UserName", id);
                }
                ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "TypeInSwedish");
                return View();
            } else {
                ViewBag.ErrorMessage = "Det finns inga lediga platser i garaget.";
                return View("Index", new Garage(db));
            }
        }

        // POST: Vehicles25/CheckIn
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CheckIn([Bind(Include = "Id,VehicleTypeId,RegNo,MemberId,NumberOfWheels,Brand,Model,Weight,ParkingSlot")] Vehicle vehicle) // XXX Behövs Exclude ParkingTíme också?
        {
            if (ModelState.IsValid) {
                if (!RegNoAlreadyCheckedIn(vehicle.RegNo)) {
                    db.Vehicles.Add(vehicle);
                    db.SaveChanges();
                    return RedirectToAction("Details", new { id = vehicle.Id });
                } else {
                    ViewBag.ErrorMessage = "Felmeddelande: Det finns redan ett fordon " +
                        "med registreringsnummer " + vehicle.RegNo + " registrerat.";
                }
            }

            ViewBag.MemberId = new SelectList(db.Members, "Id", "UserName", vehicle.MemberId);
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "TypeInSwedish", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // GET: Vehicles25/Edit/5
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null) {
                return HttpNotFound();
            }
            ViewBag.MemberId = new SelectList(db.Members, "Id", "UserName", vehicle.MemberId);
            ViewBag.VehicleTypeId = new SelectList(db.VehicleTypes, "Id", "TypeInSwedish", vehicle.VehicleTypeId);
            return View(vehicle);
        }

        // POST: Vehicles25/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
           /* [Bind(Include = "Id,VehicleTypeId,RegNo,MemberId,ParkingTime,NumberOfWheels,Brand,Model,Weight,ParkingSlot")]*/
            [Bind(Exclude = "ParkingTime")] Vehicle vehicle) {
            if (ModelState.IsValid) {
                var oldRegNo = db.Vehicles.Where(v => v.Id == vehicle.Id).Select(v => v.RegNo).FirstOrDefault();
                var oldParkTime = db.Vehicles.Where(v => v.Id == vehicle.Id).Select(v => v.ParkingTime).FirstOrDefault();
                if (oldRegNo == vehicle.RegNo || !RegNoAlreadyCheckedIn(vehicle.RegNo)) {
                    vehicle.ParkingTime = oldParkTime;
                    db.Entry(vehicle).State = EntityState.Modified;

LexiconGarage/Views/Vehicles25/AllVehicles.cshtml
@model Tuple<IEnumerable<LexiconGarage.Models.Vehicle>, LexiconGarage.Models.Vehicle>

@{
    ViewBag.Title = "Garage";
}

<h3>Fordon i garaget:</h3>

<h4 class="error-message">@ViewBag.ErrorMessage</h4>
<h4 class="info-message">@ViewBag.InfoMessage</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Item2.Id)
      
        <div class="form-group">
            @Html.LabelFor(model => model.Item2.VehicleType.TypeInSwedish, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VBagVehicleList", null, "", htmlAttributes: new { @class = "form-control", @name = "type" })
                @* Alternativ 2: @Html.DropDownListFor(model => model.Item3, new SelectList(Model.Item3, "Key", "Value"), "Välj fordon", htmlAttributes: new { @class = "dropdown-search", @id = "vehicleTypeInput", @name = "type" })*@
                @Html.ValidationMessageFor(model => model.Item2, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Item2.RegNo, htmlAttributes: new { @class = "control-label col-md-2" })
            @*<label for="regNoInput" class="title">RegNr</label>*@
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Item2.RegNo, new { @class = "form-control", @autofocus = "autofocus", @id = "regNoInput", @name = "regNo" })
                @Html.ValidationMessageFor(model => model.Item2.RegNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @*<input type="submit" class="btn btn-default" id="searchButton" value="Sök" />*@
                @*<input type="submit" class="btn btn-default" id="allButton" value="Lista alla fordon" />*@
                <input formaction="@Url.Action("AllVehiclesSearch","Vehicles25")" type="submit" class="btn btn-default" id="searchButton" value="Sök" />
                <input formaction="@Url.Action("AllVehiclesParked","Vehicles25")" type="submit" class="btn btn-default" id="allButton" value="Lista alla fordon" />
                <input formaction="@Url.Action("AllVehiclesResetSearch","Vehicles25",new { viewName="AllVehicles"})" type="submit" class="btn btn-default" id="resetButton" value="Rensa" />
                <br /><br />
            </div>
        </div>


    </div>
}


<p class="table-info">@ViewBag.SearchTableInfo</p>
@if (Model.Item1.Count() > 0)
{
    <table class="table table-bordered table-condensed table-striped table-hover sortable">
        <thead>
            <tr>
                <th data-defaultsign="AZ">@Html.DisplayNameFor(model => model.Item2.VehicleType.TypeInSwedish)</th>
                <th data-defaultsign="AZ">@Html.DisplayNameFor(model => model.Item2.RegNo)</th>
                <th data-defaultsign="AZ">@Html.DisplayNameFor(model => model.Item2.Member.UserName)</th>
                <th data-defaultsign="AZ">@Html.DisplayNameFor(model => model.Item2.ParkingTime)</th>
                <th></th>
            </tr>
        </thead>

        @foreach (var item in Model.Item1) {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.VehicleType.TypeInSwedish)</td>
                <td>@Html.DisplayFor(modelItem => item.RegNo)</td>
                <td>@Html.DisplayFor(modelItem => item.Member.UserName)</td>
                <td>@Html.DisplayFor(modelItem => item.ParkingTime)</td>
                <td>
                    @Html.ActionLink("Ändra", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Info", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Checka ut", "CheckOut", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}

LexiconGarage/Views/Vehicles25/CheckIn.cshtml
@using LexiconGarage.Models
@model LexiconGarage.Models.Vehicle

@{
    ViewBag.Title = "Parkera";
}

<h3>Parkera</h3>

<h4 class="error-message">@ViewBag.ErrorMessage</h4>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VehicleTypeId, "Fordonstyp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VehicleTypeId", null, "", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VehicleTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberId, "Användarnamn", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MemberId", null, "",htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MemberId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfWheels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfWheels, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfWheels, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Parkera" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Registrera ny medlem", "Register", "Members25")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LexiconGarage/Views/Vehicles25/CheckOut.cshtml
@model LexiconGarage.Models.Vehicle

@{
    ViewBag.Title = "Hämta ut";
}

<h3>Hämta / Checka ut</h3>

<h2>@ViewBag.Message</h2>

<h3>Följande fordon kommer att tas bort från garaget:</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.VehicleType.TypeInSwedish)</dt>
        <dd>@Html.DisplayFor(model => model.VehicleType.TypeInSwedish)</dd>

        <dt>@Html.DisplayNameFor(model => model.RegNo)</dt>
        <dd>@Html.DisplayFor(model => model.RegNo)</dd>

        <dt>@Html.DisplayNameFor(model => model.Member.UserName)</dt>
        <dd>@Html.DisplayFor(model => model.Member.UserName)</dd>

        <dt>@Html.DisplayNameFor(model => model.NumberOfWheels)</dt>
        <dd>@Html.DisplayFor(model => model.NumberOfWheels)</dd>

        <dt>@Html.DisplayNameFor(model => model.Brand)</dt>
        <dd>@Html.DisplayFor(model => model.Brand)</dd>

        <dt>@Html.DisplayNameFor(model => model.Model)</dt>
        <dd>@Html.DisplayFor(model => model.Model)</dd>

        <dt>@Html.DisplayNameFor(model => model.Weight)</dt>
        <dd>@Html.DisplayFor(model => model.Weight)</dd>

        @*<dt>@Html.DisplayNameFor(model => model.ParkingSlot)</dt>
        <dd>@Html.DisplayFor(model => model.ParkingSlot)</dd>*@

        <br />

        <dt>@Html.DisplayNameFor(model => model.ParkingTime)</dt>
        <dd>@Html.DisplayFor(model => model.ParkingTime)</dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Checka ut" class="btn btn-default" />
            <br /><br /><br />
            @Html.ActionLink("Till medlemsinfo", "Details", "Members25", new { id = Model.MemberId }, null)
        </div>
    }
</div>

LexiconGarage/Views/Vehicles25/Index.cshtml
@model LexiconGarage.Models.Garage
@{
    ViewBag.Title = "Garage";
}

<div class="jumbotron navbar-inverse">
    <h1>Garaget</h1>
    <h4 class="error-message">@ViewBag.ErrorMessage</h4>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Fordon...</h2>
        <p>
            Här kommer en del data...
        </p>
    </div>
    <div class="col-md-4">
        <h2>Beläggning</h2>
         <p>Lediga platser: @Model.EmptySlots() (av tot @Model.TotalSlots)</p>
    </div>
    <div class="col-md-4">
        <h2>Priser</h2>
        <p>@Model.Price kr/ tim (minutdebitering)</p>

    </div>
</div>